# **Task 3: Histogram Equalization**

Given the following 5x5 image, apply histogram equalization to it.

> [5,3,1,0,1,0,2,1,0,5,1,5,0,1,2,4,2,6,2,1,6,2,0,1,5]

## **Solution**

### **Step 1: Define the image**

In [1]:
import numpy as np

imgArr = np.array([5,3,1,0,1,0,2,1,0,5,1,5,0,1,2,4,2,6,2,1,6,2,0,1,5])
imgArr = imgArr.reshape(5,5)

maxVal = np.max(imgArr)

print(f'Image Bits: \n{imgArr}')
print(f'Image Shape: {imgArr.shape}')
print(f'Max Value: {maxVal}')

Image Bits: 
[[5 3 1 0 1]
 [0 2 1 0 5]
 [1 5 0 1 2]
 [4 2 6 2 1]
 [6 2 0 1 5]]
Image Shape: (5, 5)
Max Value: 6


### **Step 2: Find Histogram and Cumulative Distribution Function (CDF)**

From the above, we can see that the maximum value of this image is **6**. So, our histogram will have a size of **8** (0 to 7 / 2^3), which also means that the maximum value will change to **7**.

In [2]:
hist, _ = np.histogram(imgArr, bins=8, range=(0,7))

maxVal = 7

prob = hist / imgArr.size

cdf = np.cumsum(prob)

print(f'Histogram: {hist}')
print(f'Probability of each intensity: {prob}')
print(f'CDF: {cdf}')
print(f'New Max Value: {maxVal}')

Histogram: [5 7 5 1 1 4 2 0]
Probability of each intensity: [0.2  0.28 0.2  0.04 0.04 0.16 0.08 0.  ]
CDF: [0.2  0.48 0.68 0.72 0.76 0.92 1.   1.  ]
New Max Value: 7


### **Step 3: Find the Transfer Function**

After finding the CDF, we will find the transfer function by multiplying each value of CDF with the maximum value of the image (6).

In [3]:
S = np.floor(maxVal * cdf).astype(int)

print(f'Transfer Function: {S}')

Transfer Function: [1 3 4 5 5 6 7 7]


### **Step 4: Apply the Transfer Function**

In [4]:
newimg = S[imgArr]

print(f'Original Image: \n{imgArr}')
print(f'New Image: \n{newimg}')

Original Image: 
[[5 3 1 0 1]
 [0 2 1 0 5]
 [1 5 0 1 2]
 [4 2 6 2 1]
 [6 2 0 1 5]]
New Image: 
[[6 5 3 1 3]
 [1 4 3 1 6]
 [3 6 1 3 4]
 [5 4 7 4 3]
 [7 4 1 3 6]]
